---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: true
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  environment:
    ENVIRONMENT: "{{ lookup('env','ENVIRONMENT') }}"
    TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    TYPEORM_ENTITIES: "{{ lookup('env','TYPEORM_ENTITIES') }}"
    TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env','TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
    TYPEORM_MIGRATIONS: "{{ lookup('env','TYPEORM_MIGRATIONS') }}"
    TYPEORM_MIGRATIONS_DIR: "{{ lookup('env','TYPEORM_MIGRATIONS_DIR') }}"

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      command: sleep 10

    # - name: "install python for Ansible."
    #   # Your code here

  # tasks:
  #   - name: printing multiple environment variables
  #     debug: 
  #       msg: "{{ lookup('env', 'ENVIRONMENT', 'TYPEORM_CONNECTION', 'TYPEORM_ENTITIES', 'TYPEORM_HOST', 'TYPEORM_PORT') }}"
  #   - name: printing all the variables from remote
  #     debug:
  #       msg: "{{ ansible_env }}"

  roles:
    - configure-server