---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages."
  become: yes
  apt:
    upgrade: "yes"
  
- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: set environment variables in remote instance
  become: yes
  shell: |
    export ENVIRONMENT=production
    export TYPEORM_CONNECTION=$TYPEORM_CONNECTION
    export TYPEORM_DATABASE=$TYPEORM_DATABASE

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present